---
# tasks file for openssh

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  ignore_errors: yes

- name: Debian | Install packages
  apt:
    pkg: "{{ packages }}"
    state: present

- name: Generate Config
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    mode: "0600"
  notify:
    - Debian Restart OpenSSH
