---
# tasks file for ufw

- name: Include playbook Debian
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"


- name: Apply UFW rules
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    log: "{{ item.log }}"
  loop: "{{ ufw_rules }}"
  when: ufw_rules 

- name: Set default policy and enable
  community.general.ufw:
    policy: deny
    state: enabled
  when: ufw_rules 
