---
dependencies: []

galaxy_info:
  author: Cryobs
  description: Base system configuration for homelab
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - system
    - base
    - homelab
