---
# tasks file for docker

- name: Debian | Install dependencies 
  apt: 
    pkg:
      - apt-transport-https 
      - ca-certificates 
      - curl
      - gnupg-agent
      - software-properties-common
    state: present 
    update_cache: yes 

- name: Debian | Download Docker GPG key (armored)
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.asc
    mode: '0644'

- name: Debian | Dearmor Docker GPG key
  command: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.asc
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Debian | Set permissions on GPG key
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'

- name: Debian | Add docker repository to apt
  apt_repository:
    repo: "deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

- name: Debian | Install docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes

- name: Debian | Check docker is active
  service:
    name: docker
    state: started
    enabled: yes

- name: Debian | Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Debian | Adding ubuntu to docker group
  user:
    name: '{{ansible_user}}'
    groups: docker
    append: yes

- name: Debian | Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Debian | Change file ownership, group and permissions
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    owner: '{{ansible_user}}'
    group: '{{ansible_user}}'
